//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SankoRehber
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRehber
    {
        public int ID { get; set; }
        public string FİRMA_ADI { get; set; }
        public string LOKASYON { get; set; }
        public string DEPARTMAN { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string YETKİLİ { get; set; }
        public string DAHİLİ_1 { get; set; }
        public string DAHİLİ_2 { get; set; }
        public string DAHİLİ_3 { get; set; }
        public string TELEFON { get; set; }
        public string CEP_TELEFONU { get; set; }
        public string FAX_NO { get; set; }
    }
}
